### PR TITLE
Change parameters from pointer to ref

### PR DESCRIPTION
**Pull request by DanRStevens**
A number of methods take parameters as a pointer. After examining those methods, many of them use the parameters without first doing a null check. This implies those parameters could have been references, which are non-nullable,  or were unchecked pointers (which should probably have been references).

A few fixes and updates to parameter and method names were made along the way.

### CODE REVIEW

**Review by Brett208 — CHANGES_REQUESTED** [review]
This change does not play well with NetFixClient. 2 Errors below when compiling NetFix with this version of OP2Internal. I haven't reviewed closely yet so don't know if the fix needs to be in OP2Internal or NetFixClient.

Error (active)	E0461	initial value of reference to non-const must be an lvalue	NetFixClient	\NetFixClient\OPUNetGameSelectWnd.cpp	901	
Error	C2664	'bool OP2Internal::MultiplayerPreGameSetupWnd::ShowHostGame(OP2Internal::HostGameParameters &)': cannot convert argument 1 from 'OP2Internal::HostGameParameters *' to 'OP2Internal::HostGameParameters &'	NetFixClient	\netfixclient\opunetgameselectwnd.cpp	901

**Comment by DanRStevens** [comment]
Err, yes. Correct. Perhaps I should have been more clear about this change.

NetFixClient will also need to be updated to match. This change breaks source code compatibility (but not binary compatibility). I've made corresponding updates to NetFixClient locally, but haven't pushed them, as they won't compile without the corresponding updates from OP2Internal in place.

One of the reasons I haven't done this, is I've needed to use a branch of OP2Internal that fixes the enums so I can test compile. To test compile these changes, I'd need to merge this branch with the enum branch, or base one on top of the other, to test compile with both changes. That seemed like an awkward error prone way to develop, with extra maintenance before merging.

Now that the enum branch has been merged to master, it'll be easier to move forward on this. I'll try to push some updates to both repos, now that it's easier to manage. 

We may want to update the OP2Internal dependency before merging this though, and allow things to settle on a working build. We can push off this change until a little later.

**Comment by DanRStevens** [comment]
We may need to setup test calls to these methods in dummy test files as a way of detecting and fixing name decoration changes. Whenever parameters types are updated, even in binary compatible ways (I use that term a bit loosely), there may still be some name mangling differences.

**Review by Brett208 — APPROVED** [review]
With the changes made to this branch and the branch in NetFixClient, everything is compiling again for me. I was able to load netfix, create a lobby for a new game, click the search button, without anything obvious being wrong.

-Brett

**Pull request merged**
