### PR TITLE
Add macro to help size check structs and classes

### PR DESCRIPTION
**Pull request by DanRStevens**
This shortens the typing, while providing a standard error message with details specific to the class.

I included a couple of example uses. This pull request does not size check everything that needs to be checked. This is more to settle on a helper macro to accomplish that.

### CODE REVIEW

**Comment by DanRStevens** [comment]
Merged master for enum fixes.

I'm looking at this and wondering if the macros is really all that useful. Currently, the errors generated for a wrong size end up looking like this:
```
make
i686-w64-mingw32-g++ -MT .build/obj/DummyMain.o -MMD -MP -MF .build/obj/DummyMain.Td  -std=c++17 -g -Wall -Wno-unknown-pragmas  -c -o .build/obj/DummyMain.o DummyMain.cpp
In file included from Game/CommandPacket.h:8:0,
                 from Game/Player.h:4,
                 from Game/TethysGame.h:6,
                 from OP2Internal.h:111,
                 from DummyMain.cpp:4:
Game/../AssertSize.h:4:2: error: static assertion failed: Expected sizeof(Produce) == 9
  static_assert((Size) == sizeof(Struct), "Expected sizeof(" #Struct ") == " #Size)
  ^
Game/../AssertSize.h:4:2: note: in definition of macro ‘AssertSize’
  static_assert((Size) == sizeof(Struct), "Expected sizeof(" #Struct ") == " #Size)
  ^~~~~~~~~~~~~
makefile:36: recipe for target '.build/obj/DummyMain.o' failed
make: *** [.build/obj/DummyMain.o] Error 1
```

It doesn't list the source code location in the .cpp file where the macro was invoked. Instead, it lists where the header was included from in the source file, and the line in the macro header which expanded to the failure.

I'm wondering if we should prefer slightly more verbose static checks, that may result in better error messages. If we manually expand, the syntax difference is:
```cpp
// AssertSize(8, Produce);  // Macro, with lousy error messages
static_assert(8 == sizeof(Produce), "Expected sizeof(Produce) == 8"); // Manually expanded
```

With the manual `static_assert`, the error message is:
```
make
i686-w64-mingw32-g++ -MT .build/obj/DummyMain.o -MMD -MP -MF .build/obj/DummyMain.Td  -std=c++17 -g -Wall -Wno-unknown-pragmas  -c -o .build/obj/DummyMain.o DummyMain.cpp
In file included from Game/Player.h:4:0,
                 from Game/TethysGame.h:6,
                 from OP2Internal.h:111,
                 from DummyMain.cpp:4:
Game/CommandPacket.h:129:3: error: static assertion failed: Expected sizeof(Produce) == 8
   static_assert(9 == sizeof(Produce), "Expected sizeof(Produce) == 8");
   ^~~~~~~~~~~~~
makefile:36: recipe for target '.build/obj/DummyMain.o' failed
make: *** [.build/obj/DummyMain.o] Error 1
```

Here we get the file and line number of the `static_assert`, at a far more meaningful location. Additionally the error message is less noisy. We also don't need to add the `#include "AssertSize.h"` to all the source files with fixed sized structs.

The error message can be shortened and made more generic to reduce repetition. This should be fine as the source location meaningfully identifies the problem struct and expected size:
```cpp
static_assert(8 == sizeof(Produce), "Unexpected struct size");
```

----

Any thoughts? I'm leaning towards simpler `static_assert` statements rather than a macro.

**Comment by DanRStevens** [comment]
I thought I'd give templates a try, but didn't manage to produce anything that worked.

```cpp
template <std::size_t size, typename T>
struct AssertSize {
	enum {
		expectedSize = size,
		actualSize = sizeof(T),
		value = expectedSize == actualSize,
	};
	static_assert(value, "Unexpected size of struct");
};
```

Used as:
```cpp
AssertSize<8, Produce>;
```

Produces the following message:
```
make
i686-w64-mingw32-g++ -MT .build/obj/DummyMain.o -MMD -MP -MF .build/obj/DummyMain.Td  -std=c++17 -g -Wall -Wno-unknown-pragmas  -c -o .build/obj/DummyMain.o DummyMain.cpp
In file included from Game/Player.h:4:0,
                 from Game/TethysGame.h:6,
                 from OP2Internal.h:111,
                 from DummyMain.cpp:4:
Game/CommandPacket.h:129:3: error: declaration does not declare anything [-fpermissive]
   AssertSize<8, Produce>;
   ^~~~~~~~~~~~~~~~~~~~~~
makefile:36: recipe for target '.build/obj/DummyMain.o' failed
make: *** [.build/obj/DummyMain.o] Error 1
```

A bit of a shame it didn't work, since it identified the correct location in the source code (though for other reasons), and it is possible (though messy) to convert the compile time size values to strings for use in the error message.

**Comment by Brett208** [comment]
I think just leaving the static size checks as non template and non macros works for me. It might be a bit more verbose, but it doesn't require translating the meaning of a macro or template which will make it easier to read. And I struggle a lot finding macros worth their headache even though there are some legitimate uses for them.

Also, I like the idea of not having to include the header everywhere to get the shorter syntax.

If you want, I can wander through the structs and add the static checks like they look in OP2Utility.

**Comment by DanRStevens** [comment]
Alright. I think I'm going to close this thread as an experimental failure.

I'll briefly document the code here, for when the branch is deleted:

The helper macro:
```cpp
#define AssertSize(Size, Struct) \
    static_assert((Size) == sizeof(Struct), "Expected sizeof(" #Struct ") == " #Size)
```

Use:
```cpp
AssertSize(8, Produce);
AssertSize(12, CreateUnitInfo);
```

----

The plan going forward is slightly more verbose `static_assert`s, with fewer details in the message. Ultimately this produces better compiler error messages, which still point out all the needed info:
```cpp
static_assert(8 == sizeof(Produce), "Unexpected struct size");
```

As I've already started on this, I'll see if I can search/replace what I already have.
Edit: This seems to work for search/replace:
```
# To edit all macro calls in a header file
sed -i 's/AssertSize(\(.*\), \(.*\));/static_assert(\1 == sizeof(\2), "Unexpected struct size");/g' headerName.h
# To edit all macro calls in all header files
find . -name '*.h' -exec sed -i 's/AssertSize(\(.*\), \(.*\));/static_assert(\1 == sizeof(\2), "Unexpected struct size");/g' {} \;
# To edit all macro calls in all header files over the whole branch history
git rebase -i --exec "find . -name '*.h' -exec sed -i 's/AssertSize(\(.*\), \(.*\));/static_assert(\1 == sizeof(\2), \"Unexpected struct size\");/g' {} \; ; git add . ; git commit --amend" master

# To remove the #include line from a single header file
sed -i '/#include ".*AssertSize.h"/d'  headerName.h
# To remove the #include line from all header files
find . -name '*.h' -exec sed -i '/#include ".*AssertSize.h"/d' {} \;
# To remove the #include line from all header files over the whole branch history
git rebase -i --exec "find . -name '*.h' -exec sed -i '/#include \".*AssertSize.h\"/d' {} \; ; git add . ; git commit --amend" master
```

**Pull request closed without merging**
